version: "3"
services:
  web:
    image: kercon/angularpy:latest
    container_name: web
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    networks:
      - webnet
    links:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks: 
      - webnet
networks:
  webnet: