version: "3"
services:
  web:
    image: kercon/angularpy:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    networks:
      - webnet
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks: 
      - webnet
networks:
  webnet: